service: mousetracker
provider:
  name: aws
  runtime: nodejs12.x
  stage: 'mousetracker'
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: bin/www/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true